# -*- coding: utf-8 -*-
"""BMI_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fltEKC91kRyE51xKh8U4Zf-v53Li8Gd0
"""

# BMI Calculator

try:
    # Take weight input
    weight = float(input("Enter your weight in kg: "))

    # Take height input
    height = float(input("Enter your height in meter: "))

    # Check for invalid weight
    if weight <= 0:
        print("Weight must be greater than zero.")

    # Check for invalid height
    if height <= 0:
        print("Height must be greater than zero.")

    # Calculate BMI only if both inputs are valid
    if weight > 0 and height > 0:

        bmi = weight / (height ** 2)

        print("Your BMI is:", round(bmi, 2))

        # BMI Category
        if bmi < 18.5:
            print("Category: Underweight")

        elif bmi < 25:
            print("Category: Normal Weight")

        elif bmi < 30:
            print("Category: Overweight")

        else:
            print("Category: Obese")

        print("Thank you for using BMI Calculator!")

# Handle non-numeric input
except ValueError:
    print("Invalid input! Please enter numbers only.")

