# -*- coding: utf-8 -*-
"""Password_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQjmGtRr0hidq4Hx0OLThB8yvw4jmwAS
"""

# Random Password Generator

import random
import string

try:
    # Take password length from user
    length = int(input("Enter password length: "))

    # Validate password length
    if length < 8:
        print("Password length must be at least 8 characters.")

    else:
        # User choices
        uppercase = input("Include uppercase letters? (y/n): ").lower()
        numbers = input("Include numbers? (y/n): ").lower()
        symbols = input("Include symbols? (y/n): ").lower()

        # Default characters
        characters = string.ascii_lowercase

        if uppercase == "y":
            characters += string.ascii_uppercase

        if numbers == "y":
            characters += string.digits

        if symbols == "y":
            characters += string.punctuation

        # Generate password
        password = ""

        for i in range(length):
            password += random.choice(characters)

        print("Generated Password:", password)
        print("Thank you for using Password Generator!")

except ValueError:
    print("Invalid input! Please enter a valid number.")

